blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: mailto:support@onegrep.dev
    about: Please report security vulnerabilities via email, not GitHub issues
  - name: General Discussion
    url: https://github.com/toolprint/mcp-graphql-forge/discussions
    about: Ask questions and discuss ideas with the community
  - name: OneGrep Support
    url: https://onegrep.dev
    about: Commercial support and consulting services